language: php
php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

install:
  - composer self-update && composer --version
  - composer install --no-interaction --prefer-dist --no-autoloader

script:
  - vendor/bin/phpcs Bundles --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml

notifications:
  email: false
