rackspace-wheezy-1GB:
  - app01.project-boss.net
    grains:
#          environment: production
      roles:
        - app
        - web
#  - app02.project-boss.net:
#      minion:
#        grains:
#          environment: production
#          roles:
#            - app
#            - web
#  - data01.project-boss.net:
#      minion:
#        grains:
#          environment: production
#          roles:
#            - couchbase
#            - solr_master
#            - queue
#            - sessions
#  - data02.project-boss.net:
#      minion:
#        grains:
#          environment: production
#          roles:
#            - couchbase
#            - solr
#            - sessions

#rackspace-wheezy-1GB:
#	- jobs01
#
#rackspace-wheezy-1GB:
#	- dwh01
