rackspace-wheezy-2GB:
  - app01.prod.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - app02.prod.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - jobs01.prod.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - cronjobs

rackspace-wheezy-4GB:
  - data01.prod.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - queue
          - elasticsearch
        solr_role: master
  - data02.prod.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - elasticsearch
        solr_role: slave



#  - dwh01.project-boss.net:

