rackspace-wheezy-4GB:
  - app01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - app02.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - data01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - couchbase
          - solr_master
          - queue
  - data02.project-boss.net:
      grains:
        deployment: prod
        roles:
          - couchbase
          - solr

rackspace-wheezy-2GB:
  - jobs01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - cronjobs

#  - dwh01.project-boss.net:

