rackspace-wheezy-2GB:
  - app01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - app02.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - data01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - couchbase
          - solr
          - queue
        solr_role: master
  - data02.project-boss.net:
      grains:
        deployment: prod
        roles:
          - couchbase
          - solr
        solr_role: slave
  - jobs01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - cronjobs
        solr_role: slave

#  - dwh01.project-boss.net:

