rackspace-wheezy-1GB:
  - app01.project-boss.net:
      grains:
        environment: production
        roles:
          - app
          - web
  - app02.project-boss.net:
      grains:
        environment: production
        roles:
          - app
          - web
  - data01.project-boss.net:
      grains:
        environment: production
        roles:
          - couchbase
          - solr_master
          - queue
  - data02.project-boss.net:
      grains:
        environment: production
        roles:
          - couchbase
          - solr
  - jobs01.project-boss.net:
      grains:
        environment: production
        roles:
          - app
          - cronjobs

#  - dwh01.project-boss.net:

