prod-rackspace-wheezy-2GB:
  - app01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - app02.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - jobs01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - cronjobs

prod-rackspace-wheezy-2GB:
  - data01.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - queue
          - elasticsearch
        solr_role: master
        couchbase_role: master
  - data02.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - elasticsearch
        solr_role: slave
  - data03.project-yz.com:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - elasticsearch
        solr_role: slave



#  - dwh01.project-yz.com:

