rackspace-wheezy-2GB:
  - app01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - app02.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - web
  - jobs01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - cronjobs

rackspace-wheezy-4GB:
  - data01.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - queue
          - elasticsearch
        data_role: master
  - data02.project-boss.net:
      grains:
        deployment: prod
        roles:
          - app
          - couchbase
          - solr
          - elasticsearch
        data_role: slave



#  - dwh01.project-boss.net:

